{% set name = "jr-trapezoid" %}
{% set version = "0.0.1a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jorgenriseth/jr-trapezoid/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1f3f761ae2fcfd40724fe3ff370baad781e0c8f4b5c7b3b43e6aa47db56318a4

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed . -vv
  number: 0

requirements:
  host:
    - 'python >=3.7'
    - setuptools 
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - jr_trapezoid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jorgenriseth/jr-trapezoid
  license: MIT
  license_file: LICENSE

