[project]
name = "jr-trapezoid"
version = "0.0.1"
authors = [
    {name = "Jørgen Riseth", email="jnriseth@gmail.com"}
]
dependencies = [
    "numpy"
]


[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
